### ISSUE TITLE
Custom filter

### ISSUE THREAD

**Issue by nkoutroumanis** [MajidSas/spatialParquet#2]
Hi Majid,

In [this ](https://github.com/MajidSas/spatialParquet/blob/main/src/main/java/edu/ucr/cs/bdlab/spatialParquet/Main.java) class you mention about custom filter in line 404. Do you have any example about this? Is it possible to declare a predicate pushdown filter for repated values that handle the geometry object?

Thank you,
Nikos

**Comment by MajidSas** [comment]
Hi Nikos,
The easiest way to filter the geometries is to simply wait until the whole geometry is created, then simply filter them using a simple intersection filter. For example.

Geometry filterMBR = .... // a bounding box or any type of geometry for the area you want to filter.
if(filterMBR.intersects(newGeomObject) {
  // include it in your output
} else {
 // skip the object
}

Another more involved implementation would require passing the filter context to the GeometryMaterilizer class and possibly handle skipping the objects there as soon as an out of range value is detected. I haven't looked into this. I don't think this part would provide significant performance gains.

By default, Parquet doesn't allow filters on repeated columns. The way we handle it is to just use it to filter column groups and column chunks based on their statistics. If we also apply it to the records then, it would only filter points from geometry objects and not the entire geometry record. For this reason, I don't apply it to the records.

To make Parquet support filters for repeating columns, I had to make a small change in their source code:
https://github.com/MajidSas/parquet-mr/blob/70d461125e476712b834d68bce102a8e2456c5a9/parquet-hadoop/src/main/java/org/apache/parquet/filter2/compat/RowGroupFilter.java

I simply commented line 95, which raises an exception when we apply a filter to a repeated column. But I know I'm getting the correct results based on the way I applied it.

Let me know if anythings is unclear and if you need more help.

**Comment by nkoutroumanis** [comment]
Hi Majid, thank you for corresponding!
So, if I filter non-point objects (e.g polygon) with a predicate on the repeated values, will I get back their points that fullfill the constraint?

Thank you,
Nikos

**Comment by MajidSas** [comment]
Yes, that is what will happen. If that is what you are looking for in your use-case, you can set useRecordFilter to true. You'll have to use the modified parquet version. You can use a modified version that only comments the line I mentioned in the previous comment. You don't need the special encoding that we use, because it may not be suitable for your use-case.

**Comment by nkoutroumanis** [comment]
I am using your parquet version and I am reading parquet files via the Hadoop interface so as to manage afterwards the data in RDD.
I am handling lines with the SpatialParquet messages. However, I get the following error when I apply a filter on the repeated values. The error does not appear on repeated values that store 1 value and the filter runs correctly. Any idea how to fix this?

> org.apache.parquet.io.ParquetDecodingException: Can not read value at 1 in block 0 in file file:/Users/nicholaskoutroumanis/Documents/part-r-00000.parquet
> 	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:264)
> 	at org.apache.parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:207)
> 	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:251)
> 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
> 	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1931)
> 	at org.apache.spark.rdd.RDD.$anonfun$count$1(RDD.scala:1274)
> 	at org.apache.spark.rdd.RDD.$anonfun$count$1$adapted(RDD.scala:1274)
> 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2278)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalStateException: setResult() called on a ValueInspector whose result is already known! Did you forget to call reset()?
> 	at org.apache.parquet.filter2.recordlevel.IncrementallyUpdatedFilterPredicate$ValueInspector.setResult(IncrementallyUpdatedFilterPredicate.java:92)
> 	at org.apache.parquet.filter2.recordlevel.IncrementallyUpdatedFilterPredicateBuilder$62.update(IncrementallyUpdatedFilterPredicateBuilder.java:1216)

**Comment by MajidSas** [comment]
If I understand this trace correctly, it seems that the predicate in "IncrementallyUpdatedFilterPredicateBuilder " is already evaluated, but the code is still trying to set one of its parameters. I guess Parquet sets only one filter predicate per object, but this object has multiple records. So, you should reset the predicate after reading every record (double value) instead of every object (geometry shape).

The issue is caused by this line:
https://github.com/MajidSas/parquet-mr/blob/70d461125e476712b834d68bce102a8e2456c5a9/parquet-column/src/main/java/org/apache/parquet/filter2/recordlevel/IncrementallyUpdatedFilterPredicate.java#L90

Since the decoder must decode those values anyway, I recommend you disable this option and don't allow parquet to filter individual values. Just pass the same filter to the geometry materialiser and filter those values there instead. If there are no points in the geometry make it return an Empty Geometry object. 
When there are no more geometry objects, make it return null.

**Comment by nkoutroumanis** [comment]
Yes exactly, this causes the error. Have you managed to do this type of predicate resetting in your code for the repeated values? Maybe you have faced this error as well for the non-point objects.

Yes the other solution is the one you suggest with the materializer.

Thank you,
Nikos

**Comment by MajidSas** [comment]
We didn't have this issue because we did not filter individual points within geometries. We wanted to ensure all geometries are constructed exactly as they were written.

Here is how I'd implement this:

1- Inside getParquetReader in the main class, create a geometry representing the area you want to filter, and pass it to the initializer of the GeometryReadSupport. It will be something like this:
 new GeometryReadSupport(filterMBR)

2- Modify the GeometryReadSupport class to take the geometry object when initialized. Then, pass this object to the initalizer of the GeometryMaterializer class.

3- Similarly, you will modify the GeometryMaterializer to take this object, and you'll pass it to the GeometryUpdater class, and you'll update it to take this object when initailized.

4- Inside the GeometryUpdater, you'll modify the function appendCoordinate to check if the point is in the range before adding it. It'll be something like:

public void appendCoordinate() {
        Point p = new Point(xs[numCoords], ys[numCoords]) // use the correct syntax
        if(filterMBR.intersects(p)) {
           numCoords++;
       }
}

You'll also probably need a condition to check if this mbr is null first.

5- Inside the end function, you will check if all parts are empty, then you'll set it like:
g = gf.createEmpty(2);
and not evaluate the switch statement.

Let me know if this works, or if something is not clear.
